### ISSUE TITLE
Improper cleaning of the data yields errors

### ISSUE THREAD

**Issue by ND91** [kdkorthauer/dmrseq#11] opened 2018-05-31 16:05 UTC
First of all I would like to thank you for the dmrseq tool! I am especially curious about trying this tool out with a continuous variable. I nonetheless ran into some issues which should be relatively easy to address. 

The issue comes alight when the user does not clean all loci with non-zero coverage as described in your vignette:

`loci.idx <- which(rowSums(getCoverage(bs, type="Cov")==0) == 0)`

If any value other than 0 is used (i.e. `loci.idx <- which(rowSums(getCoverage(bs, type="Cov") >= 2) >= 2)`), then it is possible to end up with a `cov.mat` (and `meth.mat`) containing zeros. This will cause the experimental `estim` function to fail as the line `math <- meth.mat/cov.mat` will yield `NA` in that particular case, which will cause the comparison to fail in the following if-clauses as a non-numerical value is provided.

```
if (sum(mat != 0) > 0 && sum(mat != 1) > 0){
     eps <- min( min(mat[mat != 0]), 1-max(mat[mat != 1]) )
}else if (sum(mat != 0) > 0){
     eps <- min(mat[mat != 0])
}else if(sum(mat != 1) > 0){
     eps <- 1-max(mat[mat != 1])
}
```
A solution would be to change the sum functions to `sum(mat != {0|1}, na.rm = T)`. 

This is issue is not present for `getEstimatePooled()`, as the NA will simply propagate and returned as a NA in the `rawBeta`.

It would be more sensible for the user to clean their data and to keep only the CpGs with a non-zero coverage as this would likely also speed up computations due to the smaller size of the matrix.

Hope that helps!

**Comment by kdkorthauer** [comment] 2018-05-31 19:59
HI @ND91,

Thanks for your thorough and detailed bug report! I really appreciate you catching this. 

I have added `na.rm = TRUE` clauses to the lines you suggest. In addition, this required some more changes to the `getEstimate()` function. This is because the loci effects were estimated all in one step using linear algebra. Unfortunately, if some loci have missing coverage this would cause the effect estimate to be missing. What we really want is to still obtain an estimate but excluding the missing loci. One option would be to loop through a call to `lm`, for example, for each loci with a missing value. However, this will be incredibly slow if many loci have missing values. Instead, I calculated the effects using linear algebra separately for each unique missing pattern. 

For factor valued `testCovariate`, this is not an issue since `getEstimatePooled()` will only return NA for if all samples in one condition have zero coverage, but this condition is checked for in the main `dmrseq` function (see lines 347-362).

Thanks again for bringing this to my attention!

Best,
Keegan

**Comment by ND91** [comment] 2018-06-01 13:03
Hi Keegan, 

Thanks for fixing this so quickly! Unfortunately it does not work still. The error I get is:
```
Error in backsolve(R, t(Q)) : 
singular matrix in 'backsolve'. First zero in the diagonal [3].
```
A `traceback()` shows the following:
```
5: backsolve(R, t(Q))
4: getEstimate(mat = logit.mat, design = design, coeff = coeff,
       coeff.adj)
3: estim(meth.mat = meth.mat, cov.mat = cov.mat, pos = pos, chr = chr,
       design = design, coeff = coeff, coeff.adj = coeff.adj)
2: bumphunt(bs = bs, design = design, coeff = coeff, coeff.adj = coeff.adj,
       minInSpan = minInSpan, minNumRegion = minNumRegion, cutoff = cutoff,
       maxGap = maxGap, maxGapSmooth = maxGapSmooth, smooth = smooth,
       bpSpan = bpSpan, verbose = verbose, parallel = parallel,
       block = block, blockSize = blockSize, chrsPerChunk = chrsPerChunk,
       fact = fact)
1: dmrseq(bs = bsobj_filtered, testCovariate = "SJC68", adjustCovariate = c("Sex"))
```

This error also occurs both when I have and have not selected for only the non-zero CpGs. I'll do some more digging later on to see whether I can see where it has gone wrong.

**Comment by kdkorthauer** [comment] 2018-06-01 15:35
Thanks for trying again. 

Were you previously successfully able to run after selecting for non-zero CpGs?

Can you try without the `adjustCovariate` to see if that runs successfully?

**Comment by ND91** [comment] 2018-06-02 09:51
No problem.

I am currently trying dmrseq without any covariates on the non-zero CpGs, but I already notice that I am getting some other issues with regard to the parallelization (`Error in summary.connection(connection) : invalid connection`, which traces back to bplapply and sending the data to the SOCK nodes). I am currently trying out the sample data from the vignette, which appears to run fine (it is still running, but the status messages seem to get a lot further than when I run dmrseq on my own data). I will give you another update once I have more information.

**Comment by kdkorthauer** [comment] 2018-06-04 16:56
Can you try again using a fresh R session (without loading any previous workspace)? I'm wondering if the parallelization errors are due to nodes being improperly initialized/closed.

**Comment by ND91** [comment] 2018-06-05 10:28
Unfortunately it does not work, I restarted R, but the same error appears even after restarting R. I can confirm however that it works if I set `BPPARAM = MulticoreParam(workers = 1)`. Interestingly, the testing data as provided with the package seems to work fine. Based on that it appears to be my data, but there is nothing that I really see that would be peculiar about the data I am working with (besides the fact that the testing data was only for chromosome 21.

**Comment by kdkorthauer** [comment] 2018-06-05 13:47
That is strange. So that I can figure out what is happening here, would you mind sending me a minimal example that reproduces the problem (a small portion of your bsseq object that still throws the error, e.g. 1 or 2 chromosomes, along with the exact code you are using)? It would also be helpful if you could send me the output of `BiocInstaller::biocValid()` on your system.

If you don't want to post the data snippet here, you can also send me an email at keegan at jimmy dot harvard dot edu.

Thanks!

**Comment by kdkorthauer** [comment] 2018-06-22 22:17
Hi @ND91,

I was able to track down the bug causing the `backsolve` error thanks to another user who ran into the same issue sent me some example data and code. This issue has now been fixed and should be available on Bioconductor in the next day or two, provided it passes build. 

Please try again and let me know if you continue to run into problems. In particular, I'm not sure if the parallelization errors are related and if they persist I would greatly appreciate if you could send me a reproducible example with code and an example portion of your dataset that throws the error so that I can track down and fix the issue.

Thanks!
Keegan

**Closed as completed** 2019-03-01 20:49 UTC
